[package]
name = "rust_neural_network"
version = "0.1.0"
authors = ["Jonathan Woollett-Light <jonathanwoollettlight@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.18"
rand = "0.7"
scoped_threadpool = "0.1.*"
itertools = "0.8.2"